#include "main.h"
#include <WioCellLibforArduino.h>

void setup() {
	// クロック供給Off
//	__HAL_RCC_GPIOA_CLK_DISABLE();
//	__HAL_RCC_GPIOB_CLK_DISABLE();
//	__HAL_RCC_GPIOC_CLK_DISABLE();
//	__HAL_RCC_GPIOH_CLK_DISABLE();
//	__HAL_RCC_DMA1_CLK_DISABLE();
//	__HAL_RCC_DMA2_CLK_DISABLE();
//
//	__HAL_RCC_TIM5_CLK_DISABLE();
//	__HAL_RCC_WWDG_CLK_DISABLE();
//	__HAL_RCC_SPI2_CLK_DISABLE();
//	__HAL_RCC_USART2_CLK_DISABLE();
//	__HAL_RCC_I2C1_CLK_DISABLE();
//	__HAL_RCC_I2C2_CLK_DISABLE();
//	__HAL_RCC_PWR_CLK_DISABLE();
//
//	__HAL_RCC_TIM1_CLK_DISABLE();
//	__HAL_RCC_USART1_CLK_DISABLE();
//	__HAL_RCC_USART6_CLK_DISABLE();
//	__HAL_RCC_ADC1_CLK_DISABLE();
//	__HAL_RCC_SPI1_CLK_DISABLE();
//	__HAL_RCC_SYSCFG_CLK_DISABLE();
//	__HAL_RCC_TIM9_CLK_DISABLE();
//	__HAL_RCC_TIM11_CLK_DISABLE();

	// クロック供給On
//	__HAL_RCC_GPIOA_CLK_ENABLE();
//	__HAL_RCC_GPIOB_CLK_ENABLE();
//	__HAL_RCC_GPIOC_CLK_ENABLE();
//	__HAL_RCC_GPIOH_CLK_ENABLE();
//	__HAL_RCC_DMA1_CLK_ENABLE();
//	__HAL_RCC_DMA2_CLK_ENABLE();
//
//	__HAL_RCC_TIM5_CLK_ENABLE();
//	__HAL_RCC_WWDG_CLK_ENABLE();
//	__HAL_RCC_SPI2_CLK_ENABLE();
//	__HAL_RCC_USART2_CLK_ENABLE();
//	__HAL_RCC_I2C1_CLK_ENABLE();
//	__HAL_RCC_I2C2_CLK_ENABLE();
//	__HAL_RCC_PWR_CLK_ENABLE();
//
//	__HAL_RCC_TIM1_CLK_ENABLE();
//	__HAL_RCC_USART1_CLK_ENABLE();
//	__HAL_RCC_USART6_CLK_ENABLE();
//	__HAL_RCC_ADC1_CLK_ENABLE();
//	__HAL_RCC_SPI1_CLK_ENABLE();
//	__HAL_RCC_SYSCFG_CLK_ENABLE();
//	__HAL_RCC_TIM9_CLK_ENABLE();
//	__HAL_RCC_TIM11_CLK_ENABLE();
}

void loop() {
}
